#version: '3' # docker-compose v2.25.0 이상부터는 적을 필요 없어짐 (version is obsolete)
services:
  back:
    container_name: back
    build:
      context: back/
      dockerfile: Dockerfile
    environment:
      - PROFILE=local
    image: pyoun820/memebook:0.1
    ports:
      - "8080:8080"
